name: flutter_codelab_study
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  cloud_firestore: ^0.14.3

  provider: ^4.1.3   # for test

  firebase_messaging: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:    # for test
    sdk: flutter     # for test
  test: ^1.14.4      # for test
flutter:

  uses-material-design: true
